# Generated by Django 3.2.2 on 2021-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_of_rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_img', models.ImageField(default='', upload_to='images/')),
                ('standar', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=115)),
            ],
        ),
    ]
