# Generated by Django 3.2.2 on 2021-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_standar_data_of_rows_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_of_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('video_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
